// majors.js
// ============================================================
// جميع التخصصات المستخرجة من ملف تخصصات.pdf
// مع دعم الحقول المتعددة (نظام التوجيهي 2025)
// ============================================================

const MAJORS = [
    // ============================================================
    // 1. الحقل الصحي (health)
    // ============================================================
    { name: "الطب البشري", fields: ["health"], alternatives: ["طب الأسنان", "الصيدلة", "دكتور صيدلة"] },
    { name: "طب الأسنان", fields: ["health"], alternatives: ["الطب البشري", "الصيدلة"] },
    { name: "الصيدلة", fields: ["health"], alternatives: ["دكتور صيدلة", "العلوم الطبية المخبرية"] },
    { name: "دكتور صيدلة", fields: ["health"], alternatives: ["الصيدلة"] },
    { name: "الطب البيطري", fields: ["health"], alternatives: ["الإنتاج الحيواني", "الزراعة"] },
    { name: "التمريض", fields: ["health", "vocational_health"], alternatives: ["القبالة", "العلاج الطبيعي"] },
    { name: "القبالة", fields: ["health", "vocational_health"], alternatives: ["التمريض"] },
    { name: "القبالة والعناية بحديثي الولادة", fields: ["health", "vocational_health"], alternatives: ["التمريض"] },
    { name: "العلاج الطبيعي", fields: ["health"], alternatives: ["العلاج الوظيفي", "التمريض"] },
    { name: "العلاج الوظيفي", fields: ["health"], alternatives: ["العلاج الطبيعي"] },
    { name: "علوم المختبرات الطبية", fields: ["health"], alternatives: ["الأحياء", "الكيمياء"] },
    { name: "العلوم الطبية المخبرية", fields: ["health"], alternatives: ["علوم المختبرات الطبية", "الأحياء"] },
    { name: "التغذية السريرية", fields: ["health"], alternatives: ["علوم الغذاء والتغذية"] },
    { name: "التغذية السريرية والحميات", fields: ["health"], alternatives: ["علوم الغذاء والتغذية"] },
    { name: "علوم الغذاء والتغذية", fields: ["health"], alternatives: ["التغذية السريرية"] },
    { name: "الأشعة والتصوير الطبي", fields: ["health"], alternatives: ["علوم المختبرات الطبية"] },
    { name: "تكنولوجيا الأشعة الطبية", fields: ["health"], alternatives: ["الأشعة والتصوير الطبي"] },
    { name: "البصريات", fields: ["health"], alternatives: ["العلاج الطبيعي"] },
    { name: "علوم السمع والنطق", fields: ["health"], alternatives: ["العلاج الطبيعي"] },
    { name: "تكنولوجيا التخدير", fields: ["health"], alternatives: ["التمريض"] },
    { name: "الإسعاف والطوارئ", fields: ["health"], alternatives: ["التمريض"] },
    { name: "العلاج التنفسي", fields: ["health"], alternatives: ["العلاج الطبيعي"] },
    { name: "التكنولوجيا الرقمية في صناعة الأسنان", fields: ["health"], alternatives: ["طب الأسنان"] },
    { name: "فني صحة الفم والأسنان", fields: ["health"], alternatives: ["طب الأسنان"] },
    { name: "علم التجميل التطبيقي", fields: ["health"], alternatives: ["الصيدلة", "التمريض"] },

    // ============================================================
    // 2. الحقل الهندسي والعلوم والتكنولوجيا (engineering_tech)
    // ============================================================
    { name: "الهندسة المدنية", fields: ["engineering_tech"], alternatives: ["هندسة معمارية", "هندسة ميكانيكية", "هندسة صناعية"] },
    { name: "الهندسة الميكانيكية", fields: ["engineering_tech"], alternatives: ["هندسة مدنية", "هندسة كهربائية"] },
    { name: "الهندسة الكهربائية", fields: ["engineering_tech"], alternatives: ["هندسة اتصالات", "هندسة حاسوب"] },
    { name: "هندسة العمارة", fields: ["engineering_tech"], alternatives: ["هندسة مدنية", "تخطيط حضري"] },
    { name: "الهندسة الصناعية", fields: ["engineering_tech", "vocational_business"], alternatives: ["إدارة أعمال", "هندسة مدنية"] },
    { name: "هندسة المدن الذكية والمستدامة", fields: ["engineering_tech"], alternatives: ["هندسة مدنية", "تخطيط حضري"] },
    { name: "هندسة الاتصالات", fields: ["engineering_tech"], alternatives: ["هندسة كهربائية", "هندسة حاسوب"] },
    { name: "هندسة الحاسوب", fields: ["engineering_tech", "vocational_it"], alternatives: ["هندسة برمجيات", "علم الحاسوب"] },
    { name: "إنترنت الأشياء / هندسة الحاسوب", fields: ["engineering_tech", "vocational_it"], alternatives: ["هندسة حاسوب", "أمن سيبراني"] },
    { name: "هندسة القوى الكهربائية", fields: ["engineering_tech"], alternatives: ["هندسة كهربائية"] },
    { name: "هندسة النظم الطبية الحيوية", fields: ["engineering_tech"], alternatives: ["هندسة طبية", "علوم طبية"] },
    { name: "هندسة المعلوماتية الطبية الحيوية", fields: ["engineering_tech"], alternatives: ["هندسة برمجيات", "نظم معلومات صحية"] },
    { name: "الهندسة الكيميائية", fields: ["engineering_tech"], alternatives: ["الكيمياء", "هندسة صناعية"] },
    { name: "هندسة النظم الصناعية", fields: ["engineering_tech"], alternatives: ["هندسة صناعية", "إدارة أعمال"] },
    { name: "هندسة البرمجيات", fields: ["engineering_tech", "vocational_it"], alternatives: ["علم الحاسوب", "نظم معلومات"] },
    { name: "الهندسة الجيولوجية", fields: ["engineering_tech"], alternatives: ["الجيولوجيا", "هندسة مدنية"] },
    { name: "هندسة الصناعات الكيميائية", fields: ["engineering_tech"], alternatives: ["هندسة كيميائية", "الكيمياء"] },
    { name: "هندسة التعدين", fields: ["engineering_tech"], alternatives: ["الهندسة المدنية", "الجيولوجيا"] },
    { name: "هندسة الأنظمة الذكية", fields: ["engineering_tech"], alternatives: ["هندسة حاسوب", "هندسة كهربائية"] },
    { name: "هندسة المواد", fields: ["engineering_tech"], alternatives: ["الهندسة الميكانيكية", "الكيمياء"] },
    { name: "مساحة وجيوماتكس / الهندسة المدنية", fields: ["engineering_tech"], alternatives: ["الهندسة المدنية", "الجغرافيا"] },
    { name: "هندسة الميكاترونكس", fields: ["engineering_tech"], alternatives: ["هندسة ميكانيكية", "هندسة كهربائية"] },
    { name: "هندسة التخطيط الحضري والبيئي", fields: ["engineering_tech"], alternatives: ["هندسة معمارية", "تخطيط مدن"] },
    { name: "تكنولوجيا صيانة الطائرات", fields: ["engineering_tech", "vocational_industry"], alternatives: ["هندسة ميكانيكية"] },
    { name: "تقني / تكنولوجيا الأنظمة الكهربائية الذكية", fields: ["engineering_tech", "vocational_industry"], alternatives: ["هندسة كهربائية"] },
    { name: "هندسة القوى الحرارية والطاقة", fields: ["engineering_tech"], alternatives: ["هندسة ميكانيكية"] },
    { name: "هندسة المياه والبيئة", fields: ["engineering_tech"], alternatives: ["هندسة مدنية", "إدارة مياه"] },
    { name: "الهندسة النووية", fields: ["engineering_tech"], alternatives: ["هندسة كهربائية", "فيزياء"] },
    { name: "علم الحاسوب", fields: ["engineering_tech", "vocational_it"], alternatives: ["هندسة برمجيات", "نظم معلومات"] },
    { name: "نظم المعلومات الحاسوبية", fields: ["engineering_tech", "vocational_it"], alternatives: ["علم الحاسوب", "الأمن السيبراني"] },
    { name: "الأمن السيبراني", fields: ["engineering_tech", "vocational_it"], alternatives: ["علم الحاسوب", "هندسة حاسوب"] },
    { name: "علم البيانات والذكاء الاصطناعي", fields: ["engineering_tech"], alternatives: ["علم الحاسوب", "الأمن السيبراني"] },
    { name: "نظم الشبكات", fields: ["engineering_tech", "vocational_it"], alternatives: ["علم الحاسوب", "الأمن السيبراني"] },
    { name: "الرياضيات", fields: ["engineering_tech"], alternatives: ["فيزياء", "إحصاء"] },
    { name: "الفيزياء", fields: ["engineering_tech"], alternatives: ["رياضيات", "هندسة"] },
    { name: "الفيزياء التطبيقية", fields: ["engineering_tech"], alternatives: ["الفيزياء", "هندسة"] },
    { name: "الفيزياء الطبية والحيوية", fields: ["engineering_tech"], alternatives: ["الفيزياء", "العلوم الطبية"] },
    { name: "الكيمياء", fields: ["engineering_tech"], alternatives: ["علوم حياتية", "هندسة كيميائية"] },
    { name: "علوم الحياة (الأحياء)", fields: ["engineering_tech"], alternatives: ["علوم المختبرات", "الزراعة"] },
    { name: "العلوم الحياتية", fields: ["engineering_tech"], alternatives: ["الأحياء", "علوم المختبرات"] },
    { name: "الجيولوجيا", fields: ["engineering_tech"], alternatives: ["الجغرافيا", "هندسة التعدين"] },
    { name: "الجيولوجيا التطبيقية", fields: ["engineering_tech"], alternatives: ["الجيولوجيا", "الهندسة"] },
    { name: "الجيولوجيا البيئية والتطبيقية", fields: ["engineering_tech"], alternatives: ["الجيولوجيا", "البيئة"] },
    { name: "الإحصاء التطبيقي", fields: ["engineering_tech"], alternatives: ["الرياضيات", "علم البيانات"] },
    { name: "التقانات الحيوية والهندسة الوراثية", fields: ["engineering_tech"], alternatives: ["علوم الحياة", "الهندسة"] },
    { name: "نظم المعلومات الصحية", fields: ["engineering_tech", "business"], alternatives: ["علم الحاسوب", "إدارة صحية"] },
    { name: "تصميم الرسوم المتحركة والألعاب", fields: ["engineering_tech", "vocational_arts"], alternatives: ["الفنون الرقمية", "علم الحاسوب"] },
    { name: "تكنولوجيا الأفلام والوسائط المتعددة", fields: ["engineering_tech", "vocational_arts"], alternatives: ["الإعلام", "علم الحاسوب"] },
    { name: "نظم المعلومات الإدارية", fields: ["engineering_tech", "business"], alternatives: ["علم الحاسوب", "إدارة أعمال"] },

    // ============================================================
    // 3. حقل الأعمال (business)
    // ============================================================
    { name: "المحاسبة", fields: ["business", "vocational_business"], alternatives: ["إدارة أعمال", "العلوم المالية والمصرفية"] },
    { name: "المحاسبة الجنائية", fields: ["business"], alternatives: ["المحاسبة", "القانون"] },
    { name: "إدارة الأعمال", fields: ["business", "vocational_business"], alternatives: ["المحاسبة", "التسويق"] },
    { name: "اقتصاد الأعمال", fields: ["business"], alternatives: ["إدارة أعمال", "المحاسبة"] },
    { name: "العلوم المالية والمصرفية", fields: ["business"], alternatives: ["المحاسبة", "اقتصاد"] },
    { name: "الاقتصاد", fields: ["business"], alternatives: ["إدارة أعمال", "مالية"] },
    { name: "اقتصاديات المال والأعمال", fields: ["business"], alternatives: ["الاقتصاد", "المحاسبة"] },
    { name: "التسويق", fields: ["business"], alternatives: ["إدارة أعمال", "الاتصالات"] },
    { name: "التسويق الرقمي", fields: ["business"], alternatives: ["التسويق", "إدارة أعمال"] },
    { name: "التمويل", fields: ["business"], alternatives: ["العلوم المالية", "المحاسبة"] },
    { name: "التكنولوجيا المالية وإدارة المخاطر", fields: ["business"], alternatives: ["التمويل", "المحاسبة"] },
    { name: "إدارة الأزمات", fields: ["business"], alternatives: ["إدارة أعمال", "العلوم السياسية"] },
    { name: "الإدارة السياحية", fields: ["business", "vocational_tourism"], alternatives: ["إدارة فنادق", "سياحة"] },
    { name: "الإدارة الفندقية", fields: ["business", "vocational_tourism"], alternatives: ["إدارة سياحية", "سياحة"] },
    { name: "إدارة الفنادق", fields: ["business", "vocational_tourism"], alternatives: ["الإدارة السياحية"] },
    { name: "إدارة الفعاليات", fields: ["business"], alternatives: ["إدارة أعمال", "تسويق"] },
    { name: "الإدارة اللوجستية", fields: ["business", "vocational_business"], alternatives: ["إدارة أعمال", "هندسة صناعية"] },
    { name: "تكنولوجيا معلومات الأعمال", fields: ["business", "engineering_tech"], alternatives: ["نظم معلومات إدارية", "علم حاسوب"] },
    { name: "إدارة الموارد التراثية والمتاحف", fields: ["business", "humanities"], alternatives: ["الآثار", "إدارة سياحية"] },
    { name: "علم المحافظة على الآثار", fields: ["business", "humanities"], alternatives: ["الآثار", "إدارة التراث"] },
    { name: "الإدارة الضريبية والجمركية", fields: ["business"], alternatives: ["المحاسبة", "القانون"] },
    { name: "تخطيط وإدارة المشاريع", fields: ["business", "engineering_tech"], alternatives: ["إدارة أعمال", "هندسة"] },

    // ============================================================
    // 4. حقل العلوم الإنسانية والاجتماعية (humanities)
    // ============================================================
    { name: "اللغة العربية وآدابها", fields: ["humanities"], alternatives: ["اللغات", "التاريخ"] },
    { name: "اللغة العربية التطبيقية", fields: ["humanities"], alternatives: ["اللغة العربية وآدابها"] },
    { name: "اللغة الإنجليزية وآدابها", fields: ["humanities"], alternatives: ["اللغات", "الترجمة"] },
    { name: "اللغتين الروسية والإنجليزية", fields: ["humanities"], alternatives: ["اللغة الإنجليزية", "اللغات"] },
    { name: "اللغة الفرنسية التطبيقية", fields: ["humanities"], alternatives: ["اللغات", "الترجمة"] },
    { name: "الإنجليزية / اللغة الفرنسية", fields: ["humanities"], alternatives: ["اللغة الإنجليزية", "اللغة الفرنسية"] },
    { name: "الإنجليزية / اللغة التركية", fields: ["humanities"], alternatives: ["اللغة الإنجليزية", "اللغات"] },
    { name: "الإنجليزية / الإيطالية", fields: ["humanities"], alternatives: ["اللغة الإنجليزية", "اللغات"] },
    { name: "الإنجليزية / الإسبانية", fields: ["humanities"], alternatives: ["اللغة الإنجليزية", "اللغات"] },
    { name: "اللغات الأوروبية", fields: ["humanities"], alternatives: ["اللغات", "الترجمة"] },
    { name: "الترجمة التحريرية والشفوية", fields: ["humanities"], alternatives: ["اللغات", "اللغة الإنجليزية"] },
    { name: "التاريخ", fields: ["humanities"], alternatives: ["الجغرافيا", "الآثار"] },
    { name: "التاريخ والحضارة", fields: ["humanities"], alternatives: ["التاريخ", "الجغرافيا"] },
    { name: "التاريخ والحضارة الإسلامية", fields: ["humanities"], alternatives: ["التاريخ", "أصول الدين"] },
    { name: "الجغرافيا", fields: ["humanities"], alternatives: ["التاريخ", "السياحة"] },
    { name: "الجغرافيا ونظم المعلومات الجغرافية", fields: ["humanities", "engineering_tech"], alternatives: ["الجغرافيا", "نظم معلومات"] },
    { name: "الجغرافيا التطبيقية", fields: ["humanities"], alternatives: ["الجغرافيا", "التخطيط"] },
    { name: "الآثار", fields: ["humanities", "business"], alternatives: ["التاريخ", "السياحة"] },
    { name: "الآثار والسياحة", fields: ["humanities", "business"], alternatives: ["الآثار", "إدارة سياحية"] },
    { name: "الأنثروبولوجيا", fields: ["humanities"], alternatives: ["علم الاجتماع", "الآثار"] },
    { name: "صيانة المصادر التراثية وإدارتها", fields: ["humanities", "business"], alternatives: ["الآثار", "إدارة تراث"] },
    { name: "الإرشاد السياحي", fields: ["humanities", "business"], alternatives: ["إدارة سياحية", "الآثار"] },
    { name: "العلوم السياسية", fields: ["humanities"], alternatives: ["القانون", "العلاقات الدولية"] },
    { name: "العلاقات الدولية والدراسات الاستراتيجية", fields: ["humanities"], alternatives: ["العلوم السياسية", "القانون"] },
    { name: "علم الاجتماع", fields: ["humanities"], alternatives: ["الأنثروبولوجيا", "الخدمة الاجتماعية"] },
    { name: "التربية الخاصة", fields: ["humanities"], alternatives: ["علم النفس", "التربية"] },
    { name: "الإرشاد والصحة النفسية", fields: ["humanities"], alternatives: ["علم النفس", "التربية"] },
    { name: "علم النفس السريري", fields: ["humanities"], alternatives: ["الإرشاد النفسي", "التربية"] },
    { name: "معلم الصف", fields: ["humanities"], alternatives: ["التربية", "علم النفس"] },
    { name: "تربية الطفولة المبكرة", fields: ["humanities"], alternatives: ["التربية", "علم النفس"] },
    { name: "معلم التربية الفنية", fields: ["humanities", "vocational_arts"], alternatives: ["الفنون", "التربية"] },
    { name: "التربية البدنية", fields: ["humanities"], alternatives: ["علوم الرياضة", "التربية"] },
    { name: "التربية الرياضية", fields: ["humanities"], alternatives: ["التربية البدنية", "علوم الرياضة"] },
    { name: "علوم الحركة والتدريب الرياضي", fields: ["humanities"], alternatives: ["التربية البدنية", "علوم الرياضة"] },
    { name: "علم الحركة والتدريب الرياضي", fields: ["humanities"], alternatives: ["علوم الرياضة", "التربية البدنية"] },
    { name: "علوم الرياضة", fields: ["humanities"], alternatives: ["التربية الرياضية"] },
    { name: "الفنون الرقمية", fields: ["humanities", "vocational_arts"], alternatives: ["الفنون", "التصميم"] },
    { name: "الفنون الإسلامية والتطبيقية", fields: ["humanities", "vocational_arts"], alternatives: ["الفنون", "التصميم"] },
    { name: "العلاقات العامة والإعلان", fields: ["humanities"], alternatives: ["الإعلام", "التسويق"] },
    { name: "الإذاعة والتلفزيون", fields: ["humanities", "vocational_arts"], alternatives: ["الإعلام", "الصحافة"] },
    { name: "القانون", fields: ["humanities"], alternatives: ["الحقوق", "العلوم السياسية"] },
    { name: "الحقوق", fields: ["humanities"], alternatives: ["القانون", "العلوم السياسية"] },
    { name: "الشريعة", fields: ["humanities"], alternatives: ["أصول الدين", "الفقه"] },
    { name: "أصول الدين", fields: ["humanities"], alternatives: ["الشريعة", "الفقه"] },
    { name: "الفقه وأصوله", fields: ["humanities"], alternatives: ["الشريعة", "أصول الدين"] },
    { name: "الاقتصاد والمصارف الإسلامية", fields: ["humanities", "business"], alternatives: ["الشريعة", "المحاسبة"] },
    { name: "دراسات في الأديان", fields: ["humanities"], alternatives: ["أصول الدين", "التاريخ"] },
    { name: "القراءات القرآنية", fields: ["humanities"], alternatives: ["أصول الدين"] },
    { name: "الأداء الصوتي والتجويد", fields: ["humanities"], alternatives: ["القراءات القرآنية"] },
    { name: "الفقه الحنفي", fields: ["humanities"], alternatives: ["الشريعة", "الفقه"] },
    { name: "القضاء والإفتاء", fields: ["humanities"], alternatives: ["الشريعة", "القانون"] },
    { name: "الفقه الشافعي", fields: ["humanities"], alternatives: ["الشريعة"] },
    { name: "الفقه المالكي", fields: ["humanities"], alternatives: ["الشريعة"] },

    // ============================================================
    // 5. الحقول المهنية (BTEC) - جميع التخصصات المهنية
    // ============================================================
    { name: "البرمجة والدعم الفني", fields: ["vocational_it"], alternatives: ["علم الحاسوب", "هندسة برمجيات"] },
    { name: "الخدمات اللوجستية", fields: ["vocational_business"], alternatives: ["إدارة أعمال", "هندسة صناعية"] },
    { name: "صيانة المركبات", fields: ["vocational_industry"], alternatives: ["الهندسة الميكانيكية"] },
    { name: "التمديدات الكهربائية", fields: ["vocational_industry"], alternatives: ["الهندسة الكهربائية"] },
    { name: "الإنتاج الحيواني", fields: ["vocational_agriculture"], alternatives: ["الطب البيطري"] },
    { name: "الإنتاج النباتي", fields: ["vocational_agriculture"], alternatives: ["الزراعة"] },
    { name: "الطهي", fields: ["vocational_tourism"], alternatives: ["إدارة الفنادق"] },
    { name: "التصميم الجرافيكي", fields: ["vocational_arts"], alternatives: ["الفنون الرقمية", "الإعلام"] },
    { name: "وقاية النبات", fields: ["vocational_agriculture"], alternatives: ["الإنتاج النباتي", "الزراعة"] },
    { name: "الأراضي والمياه والبيئة", fields: ["vocational_agriculture", "engineering_tech"], alternatives: ["إدارة مياه", "الزراعة"] },
    { name: "تصميم وتنسيق المواقع", fields: ["vocational_agriculture", "engineering_tech"], alternatives: ["الهندسة المعمارية", "الزراعة"] },
    { name: "التغذية وتكنولوجيا الغذاء", fields: ["health", "vocational_agriculture"], alternatives: ["علوم الغذاء", "التغذية السريرية"] },
    { name: "تقنيات الوقاية والمكافحة المتكاملة", fields: ["vocational_agriculture"], alternatives: ["وقاية النبات", "الزراعة"] },
    { name: "التقنيات الحيوية الزراعية", fields: ["vocational_agriculture", "engineering_tech"], alternatives: ["الإنتاج النباتي", "التكنولوجيا الحيوية"] },
    { name: "إنتاج ووقاية النبات", fields: ["vocational_agriculture"], alternatives: ["الإنتاج النباتي", "وقاية النبات"] },
    { name: "إدارة موارد المياه والبيئة", fields: ["vocational_agriculture", "engineering_tech"], alternatives: ["الأراضي والمياه", "الزراعة"] },
    { name: "التربة والري", fields: ["vocational_agriculture"], alternatives: ["الأراضي والمياه", "الزراعة"] },
    { name: "الزراعة الرقمية", fields: ["vocational_agriculture", "engineering_tech"], alternatives: ["الزراعة", "تكنولوجيا المعلومات"] },
    { name: "تكنولوجيا وعلوم النبات", fields: ["vocational_agriculture", "engineering_tech"], alternatives: ["الإنتاج النباتي", "التكنولوجيا"] },
    { name: "تكنولوجيا وعلوم الحيوان", fields: ["vocational_agriculture", "engineering_tech"], alternatives: ["الإنتاج الحيواني", "الطب البيطري"] }
];